# Generated by Django 6.0.3 on 2026-03-21 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='detections/original/', verbose_name='原图')),
                ('annotated_image_data', models.TextField(verbose_name='标注图数据(Base64)')),
                ('pattern_type', models.CharField(max_length=100, verbose_name='纹样类型')),
                ('era_estimate', models.CharField(max_length=100, verbose_name='年代推测')),
                ('region_type', models.CharField(max_length=100, verbose_name='地域类型')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='个人备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='检测时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '检测记录',
                'verbose_name_plural': '检测记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
