# Generated by Django 6.0.3 on 2026-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionrecord",
            name="annotated_image_data",
            field=models.TextField(verbose_name="标注图数据 (Base64)"),
        ),
        migrations.AlterField(
            model_name="detectionrecord",
            name="original_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="detections/original/",
                verbose_name="原图",
            ),
        ),
    ]
