# Generated by Django 6.0.3 on 2026-03-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_alter_detectionrecord_annotated_image_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionrecord",
            name="annotated_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="detections/annotated/",
                verbose_name="标注图",
            ),
        ),
        migrations.AlterField(
            model_name="detectionrecord",
            name="annotated_image_data",
            field=models.TextField(blank=True, verbose_name="标注图数据 (Base64)"),
        ),
    ]
