# Generated by Django 6.0.3 on 2026-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_detectionrecord_annotated_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionrecord",
            name="annotated_image_data",
            field=models.TextField(
                blank=True, null=True, verbose_name="标注图数据 (Base64)"
            ),
        ),
    ]
