version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: recardomlu/tonggu-backend:latest
    container_name: tonggu-backend
    restart: always
    network_mode: "host"
    environment:
      SECRET_KEY: k8fuShpFnvtBZUdWESEQ
      DB_NAME: tonggu
      DB_USER: tonggu
      DB_PASSWORD: f3cbB2RzLCfX5wR4
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DEBUG: 'False'
      ALLOWED_HOSTS: tong-gu.cn,www.tong-gu.cn
    volumes:
      - media_data:/app/media
      - logs_data:/app/logs
    security_opt:
      - no-new-privileges:true
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 backend.wsgi:application"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 3600
    command: --interval 3600 --cleanup

volumes:
  media_data:
  logs_data:
